<a href="https://colab.research.google.com/github/Redcoder815/Machine_learning_phitron/blob/main/43KNN_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
class KNN:
  def __init__(self, k = 3):
    self.k = k

  def fit(self, X, y):
    self.X_train = X
    self.y_train = y

  def eucleadian_distance(self, x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

  def predict(self, X):
    y_pred = [self.prediction(x) for x in X]
    return np.array(y_pred)

  def prediction(self, x):
    #Compute distances between x and all examples in the training set
    distances = [self.eucleadian_distance(x, x_train) for x_train in self.X_train]
    # Sort by distance and return indices of the first k neighbors
    k_indices = np.argsort(distances)[:self.k]
    # Extract the labels of the k nearest neighbor training samples
    k_nearest_labels = [self.y_train[i] for i in k_indices]
    # Return the most common class label
    most_common = np.bincount(k_nearest_labels).argmax()
    return most_common

In [3]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

In [4]:
X, y = make_classification(n_samples = 50,
                                       n_features = 2,
                                       n_informative = 2,
                                       n_redundant = 0,
                                       n_classes = 2,
                                       weights = [0.51, .49])

In [5]:
X

array([[ 7.94853803e-01,  5.66040982e-01],
       [-8.42043727e-01,  1.38461575e+00],
       [ 7.98654173e-01,  1.66949312e+00],
       [-1.39551962e+00, -1.77014141e+00],
       [-5.38355464e-01,  5.85562722e-01],
       [-8.87856339e-01,  1.33640114e+00],
       [-3.09941557e-01,  4.76221100e-01],
       [ 1.74874831e+00, -1.97233334e+00],
       [-5.98650345e-01,  2.92776870e+00],
       [-6.21601077e-01, -1.04741703e-01],
       [-4.82991169e-01, -2.82841223e-01],
       [ 1.60161708e+00,  6.69057136e-01],
       [ 2.03708192e+00, -5.08461311e-04],
       [ 1.24208678e+00,  8.57528000e-01],
       [-1.13014564e+00,  1.26556012e+00],
       [-1.18516590e+00, -8.89088879e-01],
       [-1.23038871e+00, -1.77436454e+00],
       [ 1.58833856e+00,  6.89109403e-01],
       [ 1.37572513e+00, -4.98600322e-01],
       [ 1.57054165e+00,  1.09319130e+00],
       [-1.43665070e+00,  3.76407012e-01],
       [ 5.62858254e-01,  1.02100571e+00],
       [ 1.30934392e+00,  2.18716059e+00],
       [ 2.

In [6]:
y

array([1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1])

In [7]:
X_train, X_test,y_train, y_test = train_test_split(X,y ,
                                   random_state=104,
                                   test_size=0.25,
                                   shuffle=True)

In [8]:
X_train

array([[ 5.62858254e-01,  1.02100571e+00],
       [-2.16752270e+00, -2.43859413e+00],
       [ 1.19713383e+00, -1.60812952e+00],
       [ 2.03708192e+00, -5.08461311e-04],
       [-9.01618858e-01,  3.52617717e-01],
       [ 2.23097203e+00,  7.42115375e-01],
       [ 1.37572513e+00, -4.98600322e-01],
       [-1.75357947e+00,  5.49664004e-02],
       [-9.37712106e-01,  1.57742230e+00],
       [-3.09941557e-01,  4.76221100e-01],
       [ 1.30934392e+00,  2.18716059e+00],
       [ 1.71751838e-01, -4.54578851e-01],
       [ 7.98654173e-01,  1.66949312e+00],
       [-7.65861812e-01, -1.01518077e+00],
       [-1.18516590e+00, -8.89088879e-01],
       [-6.21601077e-01, -1.04741703e-01],
       [ 9.36102349e-02,  1.12512035e+00],
       [ 1.58833856e+00,  6.89109403e-01],
       [ 1.49529935e+00, -1.04448261e+00],
       [ 6.26783886e-01, -1.76827967e-01],
       [ 2.27349159e+00, -2.58310124e+00],
       [-6.76261270e-01,  1.65200245e+00],
       [ 1.02221089e+00, -8.51085136e-01],
       [-1.

In [9]:
y_train

array([1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0])

In [10]:
knn = KNN(k=2)
knn.fit(X_train, y_train)

In [11]:
prediction = knn.predict(X_test)

In [12]:
print("Predicted class:", prediction)
print("Actual class:", y_test)

Predicted class: [0 0 1 0 0 0 1 0 1 1 1 0 1]
Actual class: [0 0 1 0 0 0 1 1 1 1 1 0 1]
